name: Deploy to server

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Pull to server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        cd ${{ secrets.APP_PATH }}
        git reset --hard
        git pull
        npm install
        npm run build
        ${{ secrets.PM2_PATH }} startOrRestart ecosystem.config.js
        ENDSSH
    
    - name: Finish SSH
      run: |
        rm -rf ~/.ssh
